import = [
    "~/alabaster.toml",
]

[shell]
program = "wsl ~"

[window]
dimensions = { columns = 100, lines = 40 }

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 12.3

[keyboard]
bindings = [
    { key = "/", mods = "Control", chars = "\u001b[47;5u" },
    { key = ";", mods = "Control", chars = "\u001b[59;5u" },
]

[colors.primary]
background = '#F7F7F7'
foreground = '#434343'

[colors.cursor]
text = '#F7F7F7'
cursor = '#434343'

[colors.normal]
black = '#000000'
red = '#AA3731'
green = '#448C27'
yellow = '#CB9000'
blue = '#325CC0'
magenta = '#7A3E9D'
cyan = '#0083B2'
white = '#BBBBBB'

[colors.bright]
black = '#777777'
red = '#F05050'
green = '#60CB00'
yellow = '#FFBC5D'
blue = '#007ACC'
magenta = '#E64CE6'
cyan = '#00AACB'
white = '#FFFFFF'
