#!/usr/bin/env bash

alias c='clear'
alias t='tree -CL 2'
alias th='tree -hCL 2'
alias h='history'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Shortcuts
alias dl="cd ~/downloads"
alias dc="cd ~/code"
alias dt="cd ~/tmp"
alias dd="cd ~/code/dotfiles"

# git commands
alias gs='git status'
alias gb='git branch -a'
alias gc='git checkout'
alias gp='git pull'
alias gd='git diff'
alias gl='git log --all --graph --decorate --oneline'

# list files
alias l="ls -lF --color=auto"
alias lh="ls -lhF --color=auto"
alias ll="ls -lF --color=auto"
alias la="ls -lAF --color=auto"
alias lsd="ls -lF --color=auto | grep --color=never '^d'"
alias ls="command ls --color=auto"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Google Chrome
alias chrome='/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe'

# IP addresses
alias ip="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

