#!/usr/bin/env bash

# colors
blk='\[\033[01;30m\]'   # Black
red='\[\033[01;31m\]'   # Red
grn='\[\033[01;32m\]'   # Green
ylw='\[\033[01;33m\]'   # Yellow
blu='\[\033[01;34m\]'   # Blue
pur='\[\033[01;35m\]'   # Purple
cyn='\[\033[01;36m\]'   # Cyan
wht='\[\033[01;37m\]'   # White
clr='\[\033[00m\]'      # Reset

# add git branch in prompt
git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

# check if user is root
get_user() {
  if [ "$(id -u)" -eq 0 ]; then
    echo "#"
  else
    echo "$"
  fi
}

PS1="${grn}\u@\h ${ylw}\w ${red}\$(git_branch)${clr}\n\$(get_user) "
